name: XPlay
version: ${project.version}
main: com.github.xspigot.xplay
api-version: 1.16
authors: [EpicGamer73]
description: The All-In-One Minecraft Plugin
depend: [Vault]
website: https://xspigotmc.gitbook.io/
commands:
  xplay:
    description: "Main XPlay Command {xplay.main}"
    default: op
  setlobby:
    description: "Set Lobby {xplay.lobby}"
    default: op
  lobby:
    description: "Teleport To Lobby {no permission}"
    default: true